[server]
hostname = "http://localhost:9800"
query_path = "/v1/proof"
upload_path = "/v1/proof"
generate_path = "/v1/proof/payload"

[cli.params]
platform = "twitter"
#ethereum -> wallet_address, twitter-> user_name
#identity = "0x2467Ee73Bb0c5AcDeEdf4E6cC5aA685741126872"
identity = ""
#for the signature generation
persona_private_key = ""
ethereum_private_key = ""
action = "create"
proof_location = "1509404815595474945"
#get these signatures/create_at/uuid from generation api
persona_signature = "scHy8qaPdl0lK86mznifj5pSuRPEMqFc9GqKgC02I7sVrK97uIW9ydC9qfOUGNGNd/uLeN7176weHNCxGbKJdwE="
ethereum_wallet_signature = ""
create_at = "1648705013"
uuid = "875ef210-02bf-4c30-8dbf-6fe890769de6"

public_key = "0x02d7c5e01bedf1c993f40ec302d9bf162620daea93a7155cd9a8019ae3a2c2a476"


